spring.application.name=user-service

server.port: 8082

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9000

# ===============================
# MySQL Database
# ===============================
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/employee_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialecto MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# Flyway
# ===============================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
